# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_calculator"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "basic numeric expression parser"
categories = ["Expression Parser"]
keywords = ["fortran", "evaluate expressions"]
homepage = "https://github.com/urbanjost/M_calculator.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true


# new force module naming rules to avoid collisions with other packages
module-naming = true
# traditional where user can use any module name
#module-naming = false

[fortran]

# new
implicit-typing = false
implicit-external = false
source-form = "free"
#
# traditional
#implicit-typing = true
#implicit-external = true
#source-form = "default"

[library]
source-dir="src"
[dev-dependencies]
M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }
#M_framework = {namespace = "GPF"}
#M_framework.namespace    = "GPF"

[[test]]
name="runTests"
source-dir="test"
main="test_suite_M_calculator.f90"
#[test.dependencies]
#M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }
#M_framework = {namespace = "GPF"}
#M_framework.namespace    = "GPF"

[[executable]]
name="ca"
source-dir="app"
main="ca.f90"
