# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_calculator"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "basic numeric expression parser"

[library]
source-dir="src"
[dev-dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }

[[test]]
name="runTests"
source-dir="test/test_suite"
main="test_suite_M_calculator.f90"
#[test.dependencies]
#M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }

[[executable]]
name="compute"
source-dir="app"
main="compute.f90"
